### ISSUE TITLE
in-air cabling

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/ITMX_installation#10]
### TODO  
**LVDTs**  
- [X] coil to LVDT distributor
- [X] LVDT distributor to LVDT board
- [X] LVDT board to ADC

**ACCs**
- [X] accelerometer to ACC driver
- [X] ACC driver to BNC-Dsub converter
- [X] BNC-Dsub converter to ADC

**Stepping motors**
- [X] stepping motors to STM driver
- [X] STM driver to LAN hub

**BO**
- [X] BO card to BIO/BNC-converter
- [X] BIO/BNC-converter to STM driver
- [X] STM driver to each channel

**Comment by YoshinoriFujii** [comment]
**Status**  
all the cabling for ITMX tower part has done. but not all the signals are available now:
- all the LVDT signals are obtained but currently the function generator is put at IYV. and thus the signals are not available for the time being.  
- For ACCs, we have to find which driver channel would be available. also, ACC's tilt (or feedback gain as well?) might have to be tuned. 
-
