### ISSUE TITLE
cabling for circuits

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/ITMX_installation#6]
### TODO
- [ ] do cabling between the analog circuits to the ADC at IXV.

**Note**
- [ ] bring the following cables:
  - [ ] D-sub9pin, 5m -> 4
  - [ ] D-sub9pin, 15m -> 4
  - [ ] power-supply, 1.5m -> 1
  - [ ] gender changer, f-f -> more than 4
  - [ ] Ethernet cable, 15 m -> 1
